import { Pedido, Movimento } from './types';

export const MOCK_PEDIDOS: Pedido[] = [
  {
    id: '#885',
    data: '2025-07-14T20:34:42',
    empresa: 'SUA MAQUETE DESENHO TECNICO LTDA',
    cnpj: '19.775.922/0001-07',
    programa: 'Maricá (Mumbuca Verde)',
    uf: 'RJ',
    do: true,
    quantidade: 3,
    taxa: 0,
    valorTotal: 575.04,
    hashPedido: 'AB',
    auditado: true,
    status: 'ok',
    categoria: 'selo',
    createdAt: new Date().toISOString(),
  },
  {
    id: '#883',
    data: '2025-07-11T13:28:01',
    empresa: 'DELVAL COMERCIAL LTDDA',
    cnpj: '58.020.989/0002-66',
    programa: 'Amapa (SEFAZ)',
    uf: 'AP',
    do: true,
    quantidade: 1,
    taxa: 0,
    valorTotal: 191.68,
    hashPedido: 'AB',
    auditado: false,
    status: 'erro',
    categoria: 'selo',
    createdAt: new Date().toISOString(),
  },
  {
    id: '#C-001',
    data: '2025-08-01T10:00:00',
    empresa: 'ECO SUL LOGISTICA',
    cnpj: '12.345.678/0001-99',
    programa: 'SAS Tesouro Verde',
    uf: 'SP',
    do: true,
    quantidade: 150,
    taxa: 25.50,
    valorTotal: 28500.00,
    hashPedido: 'SAS-A1',
    auditado: true,
    status: 'ok',
    categoria: 'certificado_sas',
    createdAt: new Date().toISOString(),
  },
  {
    id: '#D-099',
    data: '2025-08-05T15:30:00',
    empresa: 'DMV SOLUTIONS BR',
    cnpj: '99.888.777/0001-00',
    programa: 'SAS DMV Auditoria',
    uf: 'PR',
    do: false,
    quantidade: 12,
    taxa: 10.00,
    valorTotal: 1200.00,
    hashPedido: 'DMV-X',
    auditado: false,
    status: 'pendente',
    categoria: 'sas_dmv',
    createdAt: new Date().toISOString(),
  }
];

export const MOCK_MOVIMENTOS: Movimento[] = [
  {
    id: 'MOV-001',
    pedidoId: '#885',
    raw: 'Origin: Governo Federal | Dest: Maricá | Qtd: 3 UCS | Hash: NXT-885-ALPHA',
    hashMovimento: 'NXT-885-ALPHA',
    tipo: 'gov',
    origem: 'Governo Federal / MMA',
    destino: 'Prefeitura de Maricá',
    quantidade: 3,
    duplicado: false,
    validado: true,
    createdAt: '2025-07-14T20:35:00',
  }
];
