export const COLLECTIONS = {
  accountAdjustments: 'accountAdjustments',
  aksesOrders: 'aksesOrders',
  aksesDistributorCertOrders: 'aksesDistributorCertOrders',
  aksesClientCertOrders: 'aksesClientCertOrders',
  aksesTransferOrders: 'aksesTransferOrders',
  aksesPurchaseOrders: 'aksesPurchaseOrders',
  aksesLivingCarbonOrders: 'aksesLivingCarbonOrders',
  aksesSaleOrders: 'aksesSaleOrders',
  stockAvailabilityCertOrders: 'stockAvailabilityCertOrders',
  movementIntentionOrders: 'movementIntentionOrders',
  areas: 'areas',
  consolidatedBalances: 'consolidatedBalances',
  consolidatedBalancesPerYear: 'consolidatedBalancesPerYear',
  blockedUcs: 'blockedUcs',
  cprs: 'cprs',
  distributionConfigs: 'distributionConfigs',
  distributions: 'distributions',
  financialParticipants: 'financialParticipants',
  financialBills: 'financialBills',
  financialWriteOffs: 'financialWriteOffs',
  harvests: 'harvests',
  ownershipTransfers: 'ownershipTransfers',
  platforms: 'platforms',
  platformTags: 'platformTags',
  projects: 'projects',
  ucsQuotes: 'ucsQuotes',
  roleUsers: 'roleUsers',
  transactions: 'transactions',
  tvOrders: 'tvOrders',
  tvCertificateOrders: 'tvCertificateOrders',
  tvPartners: 'tvPartners',
  tvCampaigns: 'tvCampaigns',
  tvDareRoyalties: 'tvDareRoyalties',
  tvCompensationIntents: 'tvCompensationIntents',
  ucs_batches: 'ucs_batches',
  users: 'users',
} as const;

export type CollectionName = typeof COLLECTIONS[keyof typeof COLLECTIONS];

