import { z } from 'zod';
import { fixEncoding, toFloat, toInt, toBoolean, toTimestamp } from '../core/helpers';
import { COLLECTIONS } from '../core/collections';
import { ImporterConfig } from '../core/importEngine';

export const tvCertificateOrderMapping: ImporterConfig = {
  importerKey: 'tv_certificate_orders',
  csvFile: 'plat_tesouro_verde_certificate_order.csv',
  collection: COLLECTIONS.tvCertificateOrders,
  originalTable: 'plat_tesouro_verde_certificate_order',
  schema: z.object({
    id: z.string(),
    issuer_id: z.string().optional().nullable(),
    rl_partners_campaigns_certificates_id: z.string().optional().nullable(),
    ucs_amount: z.string().optional().nullable(),
    price: z.string().optional().nullable(),
    fee: z.string().optional().nullable(),
    total: z.string().optional().nullable(),
    discount: z.string().optional().nullable(),
    commission_sum: z.string().optional().nullable(),
    status: z.string().optional().nullable(),
    payment_type: z.string().optional().nullable(),
    template_type: z.string().optional().nullable(),
    distribution_id: z.string().optional().nullable(),
    billet_id: z.string().optional().nullable(),
    basket_fee_id: z.string().optional().nullable(),
    promo_code_id: z.string().optional().nullable(),
    commission_id: z.string().optional().nullable(),
    origin_platform_id: z.string().optional().nullable(),
    recipient_platform_id: z.string().optional().nullable(),
    public_origin_platform_id: z.string().optional().nullable(),
    public_recipient_platform_id: z.string().optional().nullable(),
    public_order_book_queue_id: z.string().optional().nullable(),
    order_book_queue_id: z.string().optional().nullable(),
    responsible_document: z.string().optional().nullable(),
    responsible_name: z.string().optional().nullable(),
    all_documentation_viewed: z.string().optional().nullable(),
    additional_info: z.string().optional().nullable(),
    reason_description: z.string().optional().nullable(),
    type_reason: z.string().optional().nullable(),
    created_by: z.string().optional().nullable(),
    created_date: z.string().optional().nullable(),
    last_modified_date: z.string().optional().nullable(),
  }),
  transform: (row) => ({
    id: row.id.toString(),
    issuerId: row.issuer_id ? row.issuer_id.toString() : null,
    rlPartnersCampaignsCertificatesId: row.rl_partners_campaigns_certificates_id ? row.rl_partners_campaigns_certificates_id.toString() : null,
    ucsAmount: toFloat(row.ucs_amount),
    price: toFloat(row.price),
    fee: toFloat(row.fee),
    total: toFloat(row.total),
    discount: toFloat(row.discount),
    commissionSum: toFloat(row.commission_sum),
    status: row.status || null,
    paymentType: row.payment_type || null,
    templateType: row.template_type || null,
    distributionId: row.distribution_id ? row.distribution_id.toString() : null,
    billetId: row.billet_id ? row.billet_id.toString() : null,
    basketFeeId: row.basket_fee_id ? row.basket_fee_id.toString() : null,
    promoCodeId: row.promo_code_id ? row.promo_code_id.toString() : null,
    commissionId: row.commission_id ? row.commission_id.toString() : null,
    originPlatformId: row.origin_platform_id ? row.origin_platform_id.toString() : null,
    recipientPlatformId: row.recipient_platform_id ? row.recipient_platform_id.toString() : null,
    publicOriginPlatformId: row.public_origin_platform_id ? row.public_origin_platform_id.toString() : null,
    publicRecipientPlatformId: row.public_recipient_platform_id ? row.public_recipient_platform_id.toString() : null,
    publicOrderBookQueueId: row.public_order_book_queue_id ? row.public_order_book_queue_id.toString() : null,
    orderBookQueueId: row.order_book_queue_id ? row.order_book_queue_id.toString() : null,
    responsibleDocument: row.responsible_document || null,
    responsibleName: fixEncoding(row.responsible_name),
    allDocumentationViewed: toBoolean(row.all_documentation_viewed),
    additionalInfo: row.additional_info || null,
    reasonDescription: fixEncoding(row.reason_description),
    typeReason: row.type_reason || null,
    createdBy: row.created_by ? row.created_by.toString() : null,
    originalCreatedAt: toTimestamp(row.created_date),
    originalUpdatedAt: toTimestamp(row.last_modified_date),
  }),
};

export const tvPartnerMapping: ImporterConfig = {
  importerKey: 'tv_partners',
  csvFile: 'plat_tesouro_verde_partners.csv',
  collection: COLLECTIONS.tvPartners,
  originalTable: 'plat_tesouro_verde_partners',
  schema: z.object({
    id: z.string(),
    name: z.string().optional().nullable(),
    document: z.string().optional().nullable(),
    document_type: z.string().optional().nullable(),
    email: z.string().optional().nullable(),
    status: z.string().optional().nullable(),
  }),
  transform: (row) => ({
    id: row.id.toString(),
    name: fixEncoding(row.name),
    document: row.document || null,
    documentType: row.document_type || null,
    email: row.email || null,
    status: row.status || null,
  }),
};

export const tvCampaignMapping: ImporterConfig = {
  importerKey: 'tv_campaigns',
  csvFile: 'plat_tesouro_verde_campaigns.csv',
  collection: COLLECTIONS.tvCampaigns,
  originalTable: 'plat_tesouro_verde_campaigns',
  schema: z.object({
    id: z.string(),
    name: z.string().optional().nullable(),
    partner_id: z.string().optional().nullable(),
    status: z.string().optional().nullable(),
  }),
  transform: (row) => ({
    id: row.id.toString(),
    name: fixEncoding(row.name),
    partnerId: row.partner_id ? row.partner_id.toString() : null,
    status: row.status || null,
  }),
};

export const tvDareRoyaltyMapping: ImporterConfig = {
  importerKey: 'tv_dare_royalties',
  csvFile: 'plat_tesouro_verde_dare_royalties.csv',
  collection: COLLECTIONS.tvDareRoyalties,
  originalTable: 'plat_tesouro_verde_dare_royalties',
  schema: z.object({
    id: z.string(),
    area_id: z.string().optional().nullable(),
    amount: z.string().optional().nullable(),
    year: z.string().optional().nullable(),
    status: z.string().optional().nullable(),
    reference_date: z.string().optional().nullable(),
  }),
  transform: (row) => ({
    id: row.id.toString(),
    areaId: row.area_id ? row.area_id.toString() : null,
    amount: toFloat(row.amount),
    year: toInt(row.year) || null,
    status: row.status || null,
    referenceDate: toTimestamp(row.reference_date),
  }),
};

export const tvCompensationIntentMapping: ImporterConfig = {
  importerKey: 'tv_compensation_intents',
  csvFile: 'plat_tesouro_verde_compensation_intent.csv',
  collection: COLLECTIONS.tvCompensationIntents,
  originalTable: 'plat_tesouro_verde_compensation_intent',
  schema: z.object({
    id: z.string(),
    user_id: z.string().optional().nullable(),
    ucs_amount: z.string().optional().nullable(),
    status: z.string().optional().nullable(),
    description: z.string().optional().nullable(),
    created_date: z.string().optional().nullable(),
  }),
  transform: (row) => ({
    id: row.id.toString(),
    userId: row.user_id ? row.user_id.toString() : null,
    ucsAmount: toFloat(row.ucs_amount),
    status: row.status || null,
    description: fixEncoding(row.description),
    createdAt: toTimestamp(row.created_date),
  }),
};

export const configs = [
  tvCertificateOrderMapping,
  tvPartnerMapping,
  tvCampaignMapping,
  tvDareRoyaltyMapping,
  tvCompensationIntentMapping,
];
